### ISSUE TITLE
Current version fails to work with pylint >= 3.0

### ISSUE THREAD

**Issue by tl24** [rasjani/pylint_junit#5]
With pylint 3.0 most of the classes from pylint.interfaces have been removed.  On pylint 3.0, I get the following error loading the junit reporter:
```
  File "/home/*****/venvs/******/lib/python3.9/site-packages/pylint_junit/__init__.py", line 6, in <module>
    from pylint.interfaces import IReporter         # noqa: F401 # TODO: Report bug to flake8 tools, its is used in __implements__
ImportError: cannot import name 'IReporter' from 'pylint.interfaces' (/home/*****/venvs/*****/lib/python3.9/site-packages/pylint/interfaces.py)
```

I believe for 3.0 you would want to stop using the IReporter interface

**Comment by tl24** [comment]
I've submitted a PR to fix the issue: #6

**Comment by rasjani** [comment]
Needs a release to pypi still but issue is fixed. .
